/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewSalesRecord;

/**
 *
 * @author imdyo
 */
import Forms.ConnectionToDatabase;
import Forms.MainPanel;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
public class NewSalesRecord extends javax.swing.JFrame {
Connection conn = null;
PreparedStatement pst = null;
ResultSet rs = null;
String[] productName;
String[] quantity;
double[] amountPerRows;

public int q;
    /**
     * Creates new form NewSalesRecord
     */
    public NewSalesRecord() {
        initComponents();
        conn = ConnectionToDatabase.connectToDb();
        populateCompany();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
          ImageIcon img= new ImageIcon("E:\\Medical Store Management System\\icons\\bg.jpg");
           
           Image icon=img.getImage();
           Image scal=icon.getScaledInstance(label.getWidth(),label.getHeight(), Image.SCALE_SMOOTH);
           ImageIcon ic=new ImageIcon(scal);
           label.setIcon(ic);
           
          
          
    }
 
    public void close(){
        WindowEvent we = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }
    public void populateCompany(){
        try{
            String sql = "SELECT company_name FROM company";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
             while(rs.next()){
               companyCombo.addItem(rs.getString("company_name"));
           }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void populateCategory(){
          productCategoryCombo.removeAllItems();
        try{
            String sql = "SELECT category FROM product_category";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                productCategoryCombo.addItem(rs.getString("category"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
  public  void rate()
    {
          try{

           String sql = "SELECT price_per_unit FROM products WHERE product_name='"+productCombo.getSelectedItem()+"'";
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           if(rs.next()){
               String b=rs.getString("price_per_unit");
               
              rate1.setText(Integer.toString(Integer.parseInt(quantityTxt.getText())*Integer.parseInt(b)));
           }
        }catch(Exception e){
            
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        quantityTxt = new javax.swing.JTextField();
        productCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        companyCombo = new javax.swing.JComboBox();
        productCategoryCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        doneBtn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rate1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        doneBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        addToCartBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        quantityTxt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        quantityTxt.setEnabled(false);
        quantityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtActionPerformed(evt);
            }
        });
        quantityTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityTxtKeyReleased(evt);
            }
        });

        productCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        productCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        productCombo.setEnabled(false);
        productCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                productComboItemStateChanged(evt);
            }
        });
        productCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Product Name");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Quantity");

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Product Category", "Product Name", "Quantity", "Rate"
            }
        ));
        jScrollPane1.setViewportView(cartTable);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Company Name");

        companyCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        companyCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        companyCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                companyComboItemStateChanged(evt);
            }
        });
        companyCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyComboActionPerformed(evt);
            }
        });
        companyCombo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                companyComboPropertyChange(evt);
            }
        });

        productCategoryCombo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        productCategoryCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        productCategoryCombo.setEnabled(false);
        productCategoryCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                productCategoryComboItemStateChanged(evt);
            }
        });
        productCategoryCombo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                productCategoryComboPropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Product Category");

        doneBtn1.setBackground(new java.awt.Color(0, 204, 102));
        doneBtn1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        doneBtn1.setForeground(new java.awt.Color(255, 255, 255));
        doneBtn1.setText("Gannerate Bill");
        doneBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtn1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Rate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(companyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(12, 12, 12))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(productCategoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(quantityTxt))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(productCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(doneBtn1)))
                            .addGap(186, 186, 186)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rate1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(companyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(productCategoryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(productCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(doneBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rate1))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        backBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSalesRecord/Go-back-icon.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        doneBtn.setBackground(new java.awt.Color(0, 204, 102));
        doneBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        doneBtn.setForeground(new java.awt.Color(255, 255, 255));
        doneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSalesRecord/Accept-icon.png"))); // NOI18N
        doneBtn.setText("Confirm Purchases");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });

        removeBtn.setBackground(new java.awt.Color(204, 0, 0));
        removeBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSalesRecord/Apps-Dialog-Remove-icon.png"))); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        addToCartBtn.setBackground(new java.awt.Color(0, 153, 51));
        addToCartBtn.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addToCartBtn.setForeground(new java.awt.Color(255, 255, 255));
        addToCartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NewSalesRecord/shop-cart-add-icon.png"))); // NOI18N
        addToCartBtn.setText("Add to cart");
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Medical Store Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addToCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(897, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 2020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(444, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel)cartTable.getModel();
        model.addRow(new Object[]{companyCombo.getSelectedItem(),productCategoryCombo.getSelectedItem(), productCombo.getSelectedItem(),quantityTxt.getText(),rate1.getText()});
    
    }//GEN-LAST:event_addToCartBtnActionPerformed
    public int getSum(){
        int rowsCount  = cartTable.getRowCount();
        int sum = 0;
        for(int i=0;i < rowsCount; i++){
            sum = sum+Integer.parseInt(cartTable.getValueAt(i, 3).toString());
        }
        return sum;
    }
    public void insertAllProducts(double val){
       DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Calendar calobj = Calendar.getInstance();
        try{
            
            
       
            int rowsCount  = cartTable.getRowCount();
            for(int i =0;i < rowsCount; i++){
                q=q-Integer.parseInt(cartTable.getValueAt(i, 3).toString());
               //    JOptionPane.showMessageDialog(null, q);
                String sql  = "UPDATE products SET quantity='"+ q +"' WHERE product_name='"+ cartTable.getValueAt(i, 2).toString() +"'";
             pst = conn.prepareStatement(sql);
             pst.execute();
            
                sql  = "INSERT INTO sales_record(product_name,company_name,date_of_sale,quantity,amount) VALUES (?,?,?,?,?)";
                pst = conn.prepareStatement(sql);
                pst.setString(1, cartTable.getValueAt(i, 2).toString());
                pst.setString(2, cartTable.getValueAt(i, 0).toString());
                pst.setString(3, df.format(calobj.getTime()));
                pst.setString(4, cartTable.getValueAt(i, 3).toString());
            }
                 pst.setString(5, String.valueOf(val));
                   pst.execute();
                  
             
                 
                   
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    public void getPriceOfProductName(){
       int des = JOptionPane.showConfirmDialog(null, "Confirm Purchase?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
       if(des==0){
             try{
                    int sum= 0;
                    int rowsCount = cartTable.getRowCount();
                    for(int i=0; i<rowsCount;i++){

                        String sql = "SELECT price_per_unit,quantity FROM products WHERE product_name='"+cartTable.getValueAt(i, 2).toString()+"'";
                        pst = conn.prepareStatement(sql);
                        rs = pst.executeQuery();
                        if(rs.next()){
                            sum  += Integer.parseInt(cartTable.getValueAt(i, 3).toString()) * Double.parseDouble(rs.getString("price_per_unit"));  
                        q=Integer.parseInt(rs.getString("quantity"));
                        }
                        insertAllProducts(Double.parseDouble(cartTable.getValueAt(i, 3).toString()) * Double.parseDouble(rs.getString("price_per_unit")));
                       
                    }
                     JOptionPane.showMessageDialog(null, "Product Added");
                       
                  MainPanel m=new MainPanel();
                  m.setVisible(true);
                   close();
                   
             

                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
       }else{
           
       }
      
    }
    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        getPriceOfProductName();    
    }//GEN-LAST:event_doneBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
 MainPanel  m=new MainPanel();
     m.setVisible(true);        
        close();
    

    }//GEN-LAST:event_backBtnActionPerformed

    private void companyComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_companyComboItemStateChanged
        populateCategory();
        productCategoryCombo.enable(true);
        productCombo.enable(true);
        productCombo.removeAllItems();
        try{

           String sql = "SELECT product_name FROM products WHERE company_name='"+companyCombo.getSelectedItem()+"'";
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           while(rs.next()){
               productCombo.addItem(rs.getString("product_name"));
           }
 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_companyComboItemStateChanged

    private void productComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_productComboItemStateChanged
       
    }//GEN-LAST:event_productComboItemStateChanged

    private void companyComboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_companyComboPropertyChange
         quantityTxt.enable(true);
    }//GEN-LAST:event_companyComboPropertyChange

    private void productCategoryComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_productCategoryComboItemStateChanged
       
    }//GEN-LAST:event_productCategoryComboItemStateChanged

    private void productCategoryComboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_productCategoryComboPropertyChange
        
    }//GEN-LAST:event_productCategoryComboPropertyChange

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
          DefaultTableModel model = (DefaultTableModel)cartTable.getModel();
        if (cartTable.getSelectedRow() != -1) {
            model.removeRow(cartTable.getSelectedRow());
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    private void productComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productComboActionPerformed

    private void companyComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_companyComboActionPerformed

    private void doneBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtn1ActionPerformed
  //     MessageFormat header =new MessageFormat("print succes");
    //   try{
      // cartTable.print(JTable.PrintMode.NORMAL,header,null);
      // }catch(Exception e){
        printbill p =new printbill();
         p.tx.setText(p.tx.getText()+"                                                                                           Sanjivani Medical Bill                                                   \n\n\n\n");
          p.tx.setText(p.tx.getText()+"Product Name \t Quantity \t rate \n\n"); 
        int su=0;
        for(int i=0;i<cartTable.getRowCount();i++)
        {
            String s =cartTable.getValueAt(i,0).toString();
             String a=cartTable.getValueAt(i,1).toString();
              String d =cartTable.getValueAt(i,2).toString();
               String st =cartTable.getValueAt(i,3).toString();
                String se =cartTable.getValueAt(i,4).toString();
                su =su+Integer.parseInt(se);
               p.tx.setText(p.tx.getText()+d+"\t"+st+" \t"+se+"\n\n");
           }    
                  p.tx.setText(p.tx.getText()+"                                                                                                                                Totat rate "+su+"\n\n");
                  p.tx.setText(p.tx.getText()+"                                                                                                                                Signature\n");
                  p.setVisible(true); 
    }//GEN-LAST:event_doneBtn1ActionPerformed

    private void quantityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtActionPerformed

    private void quantityTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTxtKeyReleased
        rate();
    }//GEN-LAST:event_quantityTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSalesRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSalesRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable cartTable;
    private javax.swing.JComboBox companyCombo;
    private javax.swing.JButton doneBtn;
    private javax.swing.JButton doneBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JComboBox productCategoryCombo;
    private javax.swing.JComboBox productCombo;
    public javax.swing.JTextField quantityTxt;
    private javax.swing.JLabel rate1;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
